spring:
  application:
    name: AviaLine

  mail:
    host: smtp.gmail.com
    port: 587
    username: spotifyprm135@gmail.com
    password: rgwo vqlp qqvm eyue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/AviaLine
    username: postgres
    password: bekzhan230109

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000



  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: debug
      org.springframework.web: debug
      com.AviaLine: trace

server:
  port: 8100

end:
  point:
    user-base: /users
    user-id: /{id}
    user-create: /create
    user-update: /update/{email}
    user-delete: /delete/{id}

    role-base: /roles
    role-id: /{id}
    role-create: /create
    role-update: /update/{id}
    role-delete: /delete/{id}

    auth-base: /auth
    auth-login: /user/login
    auth-register: /user/register
    auth-confirm-code: /user/confirm-code

keys:
  access-key: yrQidcrJDGVZJ1wPWTSVoyMsZrwnNvTKzEw4vAchjWo=
  refresh-key: RMBb5tiiRxwL+KMXEqfA4zykANDFSxoZeI5ofmEgx+4=

jwt:
  access:
    expiration: 900000
  refresh:
    expiration: 1296000000

code:
  expiration: 300000

springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /api-docs