spring:
  application:
    name: AviaLine

  mail:
    host: smtp.gmail.com
    port: 587
    username: spotifyprm135@gmail.com
    password: rgwo vqlp qqvm eyue
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/AviaLine
    username: postgres
    password: bekzhan230109

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000



  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      root: debug
      org.springframework.web: debug
      com.AviaLine: debug

server:
  port: 8160

end:
  point:

    avia-base: /avia
    avia-search-params: /search-params/
    avia-privacy-policy: /privacy-policy
    avia-sirena-bill-points: /sirena/bill-points/
    avia-sirena-bill-static: /sirena/bill-static/

    base: /base
    base-countries: /api/countries/
    base-docs: /api/docs/
    base-banners: /banners/
    base-rules: /company-rules/
    base-faq: /faq/
    base-faq-slug: /faq/{slug}/
    base-info: /info/
    base-popular-directories: /popular-directories/
    base-stories: /stories/
    base-story-by-id: /stories/{id}
    base-sub-info: /sub-info/
    base-popular-direction-detail: /{id}/detail/
    base-services: /services/

    user-base: /users
    user-id: /{id}
    user-create: /create
    user-update: /update/{email}
    user-delete: /delete/{id}

    role-base: /roles
    role-id: /{id}
    role-create: /create
    role-update: /update/{id}
    role-delete: /delete/{id}

    auth-base: /auth
    auth-login: /user/login
    auth-register: /user/register
    auth-confirm-code: /user/confirm-code
    auth-delete-user: /user/delete
    auth-personal-info: /user/personal-info/
    auth-forgot-password: /user/forgot-password/
    auth-modify-password: /user/modify-password/
    auth-re-send-email: /user/re-send/email
    auth-logout: /user/logout/
    auth-modify-person-info: /user/modify-personal/

keys:
  access-key: yrQidcrJDGVZJ1wPWTSVoyMsZrwnNvTKzEw4vAchjWo=
  refresh-key: RMBb5tiiRxwL+KMXEqfA4zykANDFSxoZeI5ofmEgx+4=

app:
  admin:
    name: Isabekov Bekzhan
    email: spotifyprm135@gmail.com
    phone: 0 554 515 130
    password: bekzhan230109


jwt:
  access:
    expiration: 900000
  refresh:
    expiration: 1296000000

code:
  expiration: 300000

springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /api-docs

sirena:
  host: 193.104.87.251
  port: 34323
  timeout: 10
  msg-id: 12345
  cid: 5149